github:
  repos:
    weasylearn: cadeca/weasylearn-be
#    zuzu: apache/kafka
  tokens:
    - ghp_example_token


jenkins:
  kafka-pr: https://builds.apache.org/job/Kafka/job/kafka-2.4-jdk8/
  # pr2: https://ci-builds.apache.org/job/Kafka/job/kafka-2.3-jdk8/
